name: Sentry Upload

on:
  push:
    branches:
      - main

jobs:
  sentry-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sentry CLI
        run: npm install -g @sentry/cli

      - name: Sentry Release
        id: sentry_release
        run: |
          VERSION=$(sentry-cli releases propose-version)
          echo "::set-output name=version::$VERSION"
          yarn
          yarn build

      - name: Build and Upload Source Maps
        if: exists('build/')
        run: |
          sentry-cli releases new apple7.0
          sentry-cli releases files apple7.0 upload-sourcemaps build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kinderlabs-b6
          SENTRY_PROJECT: apple-login
