name: Sentry Upload

on:
  push:
    branches:
      - main

jobs:
  sentry-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sentry CLI
        run: npm install -g @sentry/cli

      - name: Sentry Release
        id: sentry_release
        run: |
          yarn
          yarn build

      # BUILD & DEPLOY
      - name: Check APP BUILD
        id: my-app-build
        uses: andstor/file-existence-action@v2
        with:
          files: "build/index.html"

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Source Map Upload
        if: steps.my-app-build.outputs.files_exists == 'true'
        run: |
          sentry-cli releases new ${{ steps.package-version.outputs.current-version}}
          sentry-cli releases files ${{ steps.package-version.outputs.current-version}} upload-sourcemaps build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kinderlabs-b6
          SENTRY_PROJECT: apple-login

      - name: Remove sourcemap
        if: steps.my-app-build.outputs.files_exists == 'true'
        run: |
          rm -rf build/
