name: Sentry Upload

on:
  push:
    branches:
      - main

jobs:
  sentry-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sentry CLI
        run: npm install -g @sentry/cli

      - name: Sentry Release
        id: sentry_release
        run: |
          VERSION=$(sentry-cli releases propose-version)
          echo "::set-output name=version::$VERSION"

      - name: Sentry Set Commits
        run: |
          sentry-cli releases set-commits --auto ${{ steps.sentry_release.outputs.version }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kinderlabs-b6
          SENTRY_PROJECT: vaunce-app

      - name: Build and Upload Source Maps
        run: |
          yarn build
          sentry-cli releases files ${{ steps.sentry_release.outputs.version }} upload-sourcemaps build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kinderlabs-b6
          SENTRY_PROJECT: vaunce-app
