name: Sentry Upload

on:
  push:
    branches:
      - main

jobs:
  sentry-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sentry CLI
        run: npm install -g @sentry/cli

      - name: Sentry Release
        id: sentry_release
        run: |
          VERSION=$(sentry-cli releases propose-version)
          echo "::set-output name=version::$VERSION"
          yarn

      # POS ADMIN BUILD & DEPLOY
      - name: Check POS ADMIN BUILD
        id: vaunce-app-build
        uses: andstor/file-existence-action@v2
        with:
          files: "build/index.html"

      - name: DEPLOY Firebase (Pos Admin)
        if: steps.vaunce-app-build.outputs.files_exists == 'true'
        run: |
          sentry-cli releases new apple8.0
          sentry-cli releases files apple8.0 upload-sourcemaps build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kinderlabs-b6
          SENTRY_PROJECT: apple-login

      - name: Remove sourcemap
        if: steps.vaunce-app-build.outputs.files_exists == 'true'
        run: |
          rm -rf build/
